// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExtiaChallenge.Data.Models;

public partial class TSoldier
{
    public int Id { get; set; }

    public string SoldierName { get; set; }
}